# https://www.playframework.com/documentation/latest/Configuration
akka.http{
server{
request-timeout=infinite
}
}
play.http.parser.maxMemoryBuffer=512k
play.http.parser.maxDiskBuffer=20M
play.server.max-request-size=20M

play.filters.enabled += "play.filters.cors.CORSFilter"
play.filters.enabled +="play.filters.hosts.AllowedHostsFilter"
# play.filters.enabled += "play.filters.timeout.TimeoutFilter"

play.filters.hosts{
allowed=["localhost"]
}
play.server{
http.idleTimeout=300s
}

db={
host="localhost"
port=5432
database="postgres"
uri="jdbc:postgresql://"${db.host}":"${db.port}"/"${db.database}
user=postgres
secret="Admin@159"
  maximum_pool_size = "10"
  minimum_idle_connection = "3"
}