# https://www.playframework.com/documentation/latest/Configuration
akka.http{
server{
request-timeout=infinite
}
}
play.http.parser.maxMemoryBuffer=512k
play.http.parser.maxDiskBuffer=20M
play.server.max-request-size=20M

play.filters.enabled +="play.filters.CSRFFilter"
play.filters.enabled +="play.filters.CORSFilter"
play.filters.enabled +="play.filters.hosts.AllowedHostsFilter"
play.filters.enabled += "play.filters.timeout.TimeoutFilter"

play.filters.hosts{
allowed=["localhost"]
}
play.server{
http.idleTimeout=300s
}
